- name: Deploy to GCP VM via SSH
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.GCP_HOST }}
    username: github-actions
    key: ${{ secrets.GCP_SSH_KEY }}
    command_timeout: 15m
    script: |
      cd /home/sanjanamarri2521/Vibeshift_Devops
      git fetch origin main
      git reset --hard origin/main
      docker compose down
      docker compose build
      docker compose up -d
      docker system prune -f
